import Head from "next/head";
import Image from "next/image";
import Hompeage from "../components/Hompeage";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  console.log(props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hompeage />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
